/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-10-17 23:13:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.usmp.fia.taller.login.servlet.LoginServlet;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\"\r\n");
      out.write("\tcontent=\"application/json; charset=ISO-8859-1\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/hash.js\"></script>\r\n");
      out.write("<link href=\"css/boostrap/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"css/login.css\" rel=\"stylesheet\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar login = {};\r\n");
      out.write("\tlogin.submit = function() {\r\n");
      out.write("\t\tdocument.getElementById(\"p\").value = Sha1.hash(document\r\n");
      out.write("\t\t\t\t.getElementById(\"pwd\").value);\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form action=\"login\" method=\"post\" class=\"form-signin\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"f\" value=\"signup\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\tname=\"p\" id=\"p\" value=\"\" />\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<h2 class=\"form-signin-heading\">Inicie sesión</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t<label>user:</label> -->\r\n");
      out.write("\t\t\t\t\t\t");

						String u = (String) request.getAttribute(LoginServlet.LOGINUSER);
						u = (u == null) ? "" : u;
						System.out.println("u:" + u);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"input\" name=\"u\" id=\"u\" value=\"");
      out.print(u);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Usuario\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t<label>password:</label>  -->\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" id=\"pwd\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Password\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t");

				String oWarning = (String) request
						.getAttribute(LoginServlet.WARNING);
				oWarning = (oWarning == null) ? "" : oWarning;
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label style=\"color: red\">");
      out.print(oWarning);
      out.write("</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Ingresar\"\r\n");
      out.write("\t\t\t\t\tonclick=\"return login.submit();\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-lg btn-primary btn-block\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
