/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-10-17 23:15:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_002dresources_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t<!-- Imported styles on this page -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/jvectormap/jquery-jvectormap-1.2.2.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/rickshaw/rickshaw.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bottom scripts (common) -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/gsap/main-gsap.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/joinable.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/resizeable.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/neon-api.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/jvectormap/jquery-jvectormap-1.2.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Imported scripts on this page -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/jvectormap/jquery-jvectormap-europe-merc-en.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/rickshaw/vendor/d3.v3.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/rickshaw/rickshaw.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/raphael-min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/morris.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/toastr.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/neon-chat.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScripts initializations and stuff -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/neon-custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Demo Settings -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/js/neon-demo.js\"></script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
