/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-10-17 23:15:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import edu.usmp.fia.taller.common.action.SessionParameters;
import edu.usmp.fia.taller.common.bean.Persona;
import edu.usmp.fia.taller.common.bean.Usuario;

public final class profile_002dbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Usuario oUsuario = (Usuario) request.getSession(false).getAttribute(SessionParameters.USUARIO.text());
	Persona oPersona = oUsuario.getPersona();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Profile Info and Notifications -->\r\n");
      out.write("\t<div class=\"col-md-6 col-sm-8 clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"user-info pull-left pull-none-xsm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Profile Info -->\r\n");
      out.write("\t\t\t<li class=\"profile-info dropdown\">\r\n");
      out.write("\t\t\t\t<!-- add class \"pull-right\" if you want to place this from right -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getServletContext().getContextPath());
      out.write("/resources/assets/images/thumb-1@2x.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\tclass=\"img-circle\" width=\"44\" /> ");
      out.print(oPersona.getNombre() + " " + oPersona.getApePaterno());
      out.write("</strong>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Reverse Caret -->\r\n");
      out.write("\t\t\t\t\t<li class=\"caret\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Profile sub-links -->\r\n");
      out.write("\t\t\t\t\t<li><a href=\"extra-timeline.html\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"entypo-user\"></i> Editar Perfil\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"user-info pull-left pull-right-xs pull-none-xsm\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Message Notifications -->\r\n");
      out.write("\t\t\t<li class=\"notifications dropdown\"><a href=\"#\"\r\n");
      out.write("\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\tdata-hover=\"dropdown\" data-close-others=\"true\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"entypo-mail\"></i> <span class=\"badge badge-info\">6</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"top-dropdown-search\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Search anything...\" name=\"s\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu-list scroller\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"image pull-right\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/images/thumb-1.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> <span class=\"line\"> <strong>Luc Chartier</strong> -\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tyesterday\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> <span class=\"line desc small\"> This ainât our first\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\titem, it is the best of the rest. </span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"external\"><a href=\"correo.html\">Ver todos\r\n");
      out.write("\t\t\t\t\t\t\tlos mensajes</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Raw Links -->\r\n");
      out.write("\t<div class=\"col-md-6 col-sm-4 clearfix hidden-xs\">\r\n");
      out.write("\r\n");
      out.write("\t\t<ul class=\"list-inline links-list pull-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Language Selector -->\r\n");
      out.write("\t\t\t<li class=\"dropdown language-selector\">Idioma: &nbsp; <a\r\n");
      out.write("\t\t\t\thref=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\tdata-close-others=\"true\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/images/flag-es.png\" />\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"dropdown-menu pull-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getServletContext().getContextPath() );
      out.write("/resources/assets/images/flag-es.png\" /> <span>Español</span>\r\n");
      out.write("\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"#\" data-toggle=\"chat\" data-collapse-sidebar=\"1\">\r\n");
      out.write("\t\t\t\t\t<i class=\"entypo-chat\"></i> Chat <span\r\n");
      out.write("\t\t\t\t\tclass=\"badge badge-success chat-notifications-badge is-hidden\">0</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li class=\"sep\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<li><a href=\"extra-login.html\"> Salir <i\r\n");
      out.write("\t\t\t\t\tclass=\"entypo-logout right\"></i>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
